"""Policy oracle for the refunds domain (session-2 guide 4a.4). Single
source of truth for both task generation and per-turn compliance grading
-- pure functions, no side effects, no tool calls.

Scope note: R1 (identity + explicit confirmation) and R10 (one write
action per order per conversation) are properties of the *conversation*,
not of a single (order, request) snapshot, so they aren't decidable from
this module's pure functions alone. Mirrors the guide's own design for
retail's native compliance rules (session-2 guide 4b.2: "a small
deterministic matcher" implemented at the canonicalization layer, not in
the oracle) -- R1/R10 are checked in envs/tau2/refunds_canonical.py.

D3 policy-tightening ambiguity, resolved and documented here rather than
silently: the guide's D3 spec moves R3's upper bound from 60 to 45 days
but doesn't say what happens to R4's "after 60 days" for the 46-60 day
gap this opens up. Resolved by making R4 apply whenever a day count
exceeds R3's *current* upper bound (45 under D3, 60 under the base
policy) -- R4's rule_id keeps meaning "too late for any return", which
is the only reading that doesn't leave a silent gap with no rule at all.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

from change.contracts import PolicyEval
from envs.tau2.domains.refunds.data_model import CURRENT_TIME, Customer, Order, Product

PolicyVersion = Literal["v1", "v3"]  # v1 = base policy.md, v3 = D3's policy_d3.md

_R2_DAYS = {"v1": 30, "v3": 20}
_R3_DAYS = {"v1": 60, "v3": 45}
_R3_THRESHOLD = {"v1": 250.0, "v3": 150.0}
_R8_REFUND_THRESHOLD = 100.0
_R8_MIN_PRIOR_REFUNDS = 2

RequestType = Literal["return", "exchange", "cancel"]


class RefundRequest(BaseModel):
    """A customer's request, as generated by a task or inferred from a live
    conversation. `item_ids` defaults to every item on the order."""

    request_type: RequestType
    order_id: str
    item_ids: list[str] = Field(default_factory=list)
    new_product_ids: list[str] = Field(default_factory=list)  # exchange only
    wants_human: bool = False


TakenAction = tuple[str, dict]


def _now() -> datetime:
    return datetime.fromisoformat(CURRENT_TIME)


def _days_since_delivery(order: Order) -> float | None:
    if order.delivered_at is None:
        return None
    delivered = datetime.fromisoformat(order.delivered_at)
    return (_now() - delivered).total_seconds() / 86400.0


def _is_gift_card(order: Order, customer: Customer) -> bool:
    for pm in customer.payment_methods:
        if pm.id == order.payment_method_id:
            return pm.type == "gift_card"
    return False


def _refund_amount(order: Order, request_type: RequestType) -> float:
    return order.total if request_type == "return" else order.total * 0.5


def _apply_r7_r8(
    order: Order, customer: Customer, request_type: RequestType, base_action: TakenAction
) -> TakenAction:
    """R7 (gift-card refunds not permitted) then R8 (frequent refunders
    escalate over-100 refunds), applied on top of an otherwise-compliant
    refund_full/refund_partial decision."""
    if _is_gift_card(order, customer):
        return ("deny_request", {"order_id": order.order_id, "reason": "gift_card_refund_not_permitted"})
    if (
        order.prior_refunds_12m >= _R8_MIN_PRIOR_REFUNDS
        and _refund_amount(order, request_type) > _R8_REFUND_THRESHOLD
    ):
        return ("escalate", {"order_id": order.order_id, "reason": "frequent_refunder_over_threshold"})
    return base_action


def _expected_return_or_exchange(
    order: Order,
    request: RefundRequest,
    customer: Customer,
    products: dict[str, Product],
    policy_version: PolicyVersion,
) -> TakenAction:
    if order.status != "delivered":
        return ("deny_request", {"order_id": order.order_id, "reason": "order_not_delivered"})

    days = _days_since_delivery(order)
    assert days is not None  # status == "delivered" implies delivered_at is set
    r2_days = _R2_DAYS[policy_version]
    r3_days = _R3_DAYS[policy_version]
    r3_threshold = _R3_THRESHOLD[policy_version]

    item_ids = request.item_ids or [item.item_id for item in order.items]

    if request.request_type == "exchange":
        if days > r2_days:
            return ("deny_request", {"order_id": order.order_id, "reason": "exchange_window_expired"})
        original_categories = {
            products[item.product_id].category for item in order.items if item.item_id in item_ids
        }
        new_categories = {products[pid].category for pid in request.new_product_ids if pid in products}
        if not request.new_product_ids or new_categories != original_categories:
            return ("deny_request", {"order_id": order.order_id, "reason": "exchange_category_mismatch"})
        return (
            "exchange_items",
            {
                "order_id": order.order_id,
                "item_ids": item_ids,
                "new_product_ids": request.new_product_ids,
            },
        )

    # request.request_type == "return"
    if days <= r2_days:
        return _apply_r7_r8(
            order, customer, "return", ("refund_full", {"order_id": order.order_id})
        )
    if days <= r3_days:
        if order.total >= r3_threshold:
            return ("escalate", {"order_id": order.order_id, "reason": "high_value_partial_refund_window"})
        return _apply_r7_r8(
            order, customer, "return", ("refund_partial", {"order_id": order.order_id, "percent": 50})
        )
    # days > r3_days: too late for any return (R4)
    if order.damage_reported:
        return ("escalate", {"order_id": order.order_id, "reason": "damage_reported_past_window"})
    return ("deny_request", {"order_id": order.order_id, "reason": "past_return_window"})


def expected_action(
    order: Order,
    request: RefundRequest,
    customer: Customer,
    products: dict[str, Product],
    policy_version: PolicyVersion = "v1",
) -> TakenAction:
    """The single compliant (tool_name, args) for this (order, request,
    customer) under the given policy version. R9's "escalate on explicit
    human request" is checked first since it overrides everything else."""
    if request.wants_human:
        return ("escalate", {"order_id": order.order_id, "reason": "customer_requested_human"})

    if request.request_type == "cancel":
        if order.status == "pending":
            return ("cancel_order", {"order_id": order.order_id})
        return ("deny_request", {"order_id": order.order_id, "reason": "order_not_pending"})

    return _expected_return_or_exchange(order, request, customer, products, policy_version)


def check(
    order: Order,
    request: RefundRequest,
    customer: Customer,
    products: dict[str, Product],
    taken: TakenAction,
    policy_version: PolicyVersion = "v1",
) -> PolicyEval:
    """Compares `taken` against `expected_action`. Compliant iff the tool
    name and every argument match exactly (arg order-independent)."""
    expected_name, expected_args = expected_action(order, request, customer, products, policy_version)
    taken_name, taken_args = taken

    if taken_name == expected_name and taken_args == expected_args:
        return PolicyEval(compliant=True, violated_rule_ids=[])

    violated = _violated_rule_ids(order, request, customer, products, policy_version, expected_name)
    return PolicyEval(compliant=False, violated_rule_ids=violated)


_RULE_FOR_REASON = {
    "order_not_pending": ["R6"],
    "gift_card_refund_not_permitted": ["R7"],
    "frequent_refunder_over_threshold": ["R8"],
    "exchange_window_expired": ["R5"],
    "exchange_category_mismatch": ["R5"],
    "high_value_partial_refund_window": ["R3"],
    "damage_reported_past_window": ["R4"],
    "past_return_window": ["R4"],
    "order_not_delivered": ["R2", "R5"],
    "customer_requested_human": ["R9"],
}


def _violated_rule_ids(
    order: Order,
    request: RefundRequest,
    customer: Customer,
    products: dict[str, Product],
    policy_version: PolicyVersion,
    expected_name: str,
) -> list[str]:
    """Best-effort attribution of which numbered rule the expected action
    was grounded in, for grading/reporting. Falls back to the rule
    governing the action type itself when no specific reason applies."""
    _, expected_args = expected_action(order, request, customer, products, policy_version)
    reason = expected_args.get("reason")
    if reason in _RULE_FOR_REASON:
        return _RULE_FOR_REASON[reason]
    if expected_name in ("refund_full",):
        return ["R2"]
    if expected_name == "refund_partial":
        return ["R3"]
    if expected_name == "exchange_items":
        return ["R5"]
    if expected_name == "cancel_order":
        return ["R6"]
    return ["R9"]
